#!/bin/bash

#SBATCH -n 1
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=10G
#SBATCH --job-name="GEO"
#SBATCH --mail-user=eboileau@uni-heidelberg.de

# source ~/.virtualenvs/dhart_utils/bin/activate

FILE=/prj/DHART/dhart-utils/ACCESSION.txt
LOG=/prj/DHART/dhart-utils/logs/scRNASeq/ACCESSION.log
DIR=/prj/DHART/DATA/scRNASeq
./accession.py -d $DIR -f $FILE  --logging-level INFO --log-file $LOG

